spring:
    application:
        name: gateway-server
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: user-service
                          uri: lb://user-service
                          predicates:
                            - Path=/api/users/**
                        - id: product-service
                          uri: lb://product-service
                          predicates:
                            - Path=/api/products/**
                        - id: cart-service
                          uri: lb://cart-service
                          predicates:
                            - Path=/api/carts/**
                        - id: order-service
                          uri: lb://order-service
                          predicates:
                            - Path=/api/orders/**
               
server:
    port: 8888

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
